# @name createAccount1
POST http://localhost:5015/accounts
content-type: application/json

{
  "accountHolder": "Somying 422R",
  "initialDeposit": 1000.0
}

###

@transferToAccountId = {{createAccount1.response.body.$.id}}

###
# @name createAccount2
POST http://localhost:5015/accounts
content-type: application/json

{
  "accountHolder": "John Doe",
  "initialDeposit": 1000.0
}

###
@accountId = {{createAccount2.response.body.$.id}}

###

GET http://localhost:5015/accounts/{{accountId}}

###

POST http://localhost:5015/accounts/{{accountId}}/deposit
content-type: application/json

{
  "amount": 500.0
}

###
POST http://localhost:5015/accounts/{{accountId}}/withdraw
content-type: application/json

{
  "amount": 200.0
}

###
POST http://localhost:5015/accounts/{{accountId}}/transfer
content-type: application/json

{
  "toAccountNumber": "{{transferToAccountId}}",
  "amount": 300.0 
}

###
POST http://localhost:5015/accounts/{{accountId}}/withdraw
content-type: application/json

{
  "amount": 200.0
}

###
DELETE http://localhost:5015/accounts/{{accountId}}

###

GET http://localhost:5015/accounts/{{accountId}}
